#Config file for Sidekiq
:concurreny: 2
:queues:
    - [mailer,5]
    - [default,5]

#if Rails.env.production?
# Sidekiq.configure_server do |config|
# config.redis = { url: ENV["REDISTOGO_URL"]}
#end
